import re
from collections import Counter

from sqlalchemy.orm import Session

from app.models.entities import Job, Candidate, RequirementScore, MatchLevel, MatchResult


def _tokenize(text: str) -> list[str]:
    return re.findall(r"[a-zA-Z0-9+#.]+", text.lower())


def _evaluate_requirement(requirement: str, candidate_text: str) -> tuple[float, str, str, str]:
    req_tokens = [t for t in _tokenize(requirement) if len(t) > 2]
    cand_tokens = Counter(_tokenize(candidate_text))
    hits = [t for t in req_tokens if cand_tokens[t] > 0]

    if not req_tokens:
        return 0.0, 'Low', '', 'Clearly Missing'

    coverage = len(hits) / max(1, len(set(req_tokens)))

    if coverage >= 0.7:
        return 1.0, 'High', ', '.join(hits[:8]), 'Strongly Demonstrated'
    if coverage >= 0.3:
        return 0.5, 'Medium', ', '.join(hits[:8]), 'Partially Demonstrated'
    return 0.0, 'Low', '', 'Clearly Missing'


def match_level_for_score(score: float) -> MatchLevel:
    if score >= 80:
        return MatchLevel.strong
    if score >= 65:
        return MatchLevel.moderate
    return MatchLevel.weak


def score_candidate_for_job(db: Session, candidate: Candidate, job: Job) -> MatchResult:
    db.query(RequirementScore).filter(
        RequirementScore.candidate_id == candidate.id,
        RequirementScore.job_id == job.id,
    ).delete()

    total = 0.0
    possible = 0.0
    risk_flag = False

    for req in job.requirements:
        score, confidence, evidence, gap_type = _evaluate_requirement(req.requirement_text, candidate.raw_text)
        possible += 1.0
        total += score
        if req.requirement_type.value == 'mandatory' and score == 0.0:
            risk_flag = True

        db.add(
            RequirementScore(
                candidate_id=candidate.id,
                job_id=job.id,
                requirement_id=req.id,
                score=score,
                confidence=confidence,
                evidence=evidence,
                gap_type=gap_type,
                notes='Generated by rule-based open-source scorer',
            )
        )

    total_percent = round((total / possible) * 100, 2) if possible else 0.0
    match_level = match_level_for_score(total_percent)

    summary = (
        f"Candidate {candidate.full_name} is a {match_level.value} match for {job.title} "
        f"with {total_percent}% score."
    )
    interview_questions = [
        'Can you share a concrete project example for missing or partial requirements?',
        'Which tools and technologies did you use most recently?',
        'Tell us about impact and ownership in your last role.',
    ]
    outreach_email = (
        f"Hi {candidate.full_name},\n\n"
        f"Your profile appears relevant for {job.title}. We'd like to discuss your experience.\n\n"
        'Best regards,\nRecruitment Team'
    )

    result = db.query(MatchResult).filter(
        MatchResult.candidate_id == candidate.id,
        MatchResult.job_id == job.id,
    ).first()

    if result is None:
        result = MatchResult(candidate_id=candidate.id, job_id=job.id)
        db.add(result)

    result.total_score_percent = total_percent
    result.match_level = match_level
    result.risk_flag = risk_flag
    result.summary = summary
    result.interview_questions = interview_questions
    result.outreach_email = outreach_email

    db.commit()
    db.refresh(result)
    return result
